version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    container_name: chat-service
    depends_on:
      database:
        condition: service_healthy
    database:
      image: cassandra:latest
      